language: php
php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - hhvm
before_install:
  - composer show --platform
install:
  - composer install
after_script:
  - vendor/bin/test-reporter --coverage-report tests/output/clover.xml
addons:
  code_climate:
