language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
before_install:
  - composer show --platform
install:
  - composer install
after_script:
  - vendor/bin/test-reporter --coverage-report tests/output/clover.xml
addons:
  code_climate:
