name: default
on: [push]
jobs:
  php-cs-fixer:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Task
        run: curl -sL https://taskfile.dev/install.sh | sh
      - name: Lint
        run: ./bin/task lint
  tests:
    name: Test
    strategy:
      matrix:
        php: ["5.6", "7.0", "7.1", "7.2", "7.3", "7.4"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Task
        run: curl -sL https://taskfile.dev/install.sh | sh
      - name: Test
        run: PHP_VERSION=${{ matrix.php }} ./bin/task test
