name: default
on: [push]
jobs:
    php-cs-fixer:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Install Task
              run: curl -sL https://taskfile.dev/install.sh | sh
            - name: Lint
              run: ./bin/task lint
